#------------[HardcoreSurival]------------#
# A hardcore survival world plugin

# Developed by 10becja
# Check us out at play.minecraft.dk
#-----------------------------------------#

#What to color death messages
#use normal Minecraft color codes 0-9 a-f
msgColor: f

#You can use this to draw extra attention to the coords
coordsColor: f

#The message that's displayed to banned players
banMsg: "You've died! Better luck next time"

#protect new players?
newPlayerProtection: true

#how long to protect new players (in minutes)
newbieTimer: 30

#Whether or not to announce cross server
announce: false