name: HardcoreSurvival
version: 1.0
main: me.becja10.HardcoreSurvival.Main
softdepend: [Essentials]
description: Hardcore wrapper plugin for servers running GriefPrevention and Essentials
author: 10becja