name: HardcoreSurvival
version: 1.5
main: me.becja10.HardcoreSurvival.HardcoreSurvival
description: i dunno yet
commands:
  setbase:
    description: Stores your location so that you can find your way back with a compass
    usage: /<command>
  hardcorereload:
    description: reloads the player database
    usage: /<command>
    aliases: [hcr]
  reloadplayers:
    usage: /<command>