name: HardcoreSurvival
version: 1.5
main: me.becja10.HardcoreSurvival.HardcoreSurvival
description: i dunno yet
commands:
  setbase:
    description: Stores your location so that you can find your way back with a compass
    usage: /<command>
  hardcorereload:
    description: reloads the player database
    usage: /<command>
    aliases: [hcr]
  reloadplayers:
    usage: /<command>
  target:
    description: Used by zombies to target location or players
    usage: /<command> <playername>
  removeprotection:
    description: Used if you want to remove your newbie status early
    usage: /<command>
  spawnboss:
    description: Spawns a boss mob at location
    usage: /<command> <mob type>
  lost:
    description: Gives you a compass if you need one
    usage: /<command>
  hstop:
    description: Shows the top 10 players
    usage: /<command>
  hsrank:
    description: Shows your or another player's rank and score
    usage: /<command> (player)
  hsstats:
    description: View hardcore stats
    usage: /<command> (player)