name: HardcoreSurvival
version: 2.0
main: me.becja10.HardcoreSurvival.HardcoreSurvival
description: Adds new features to make regular survival a bit more interesting. Introduces ZOMBIE PLAYERS!
commands:
  setbase:
    description: Stores your location so that you can find your way back with a compass
    usage: /<command>
  hardcorereload:
    description: reloads the player database
    usage: /<command>
  target:
    description: Used by zombies to target location or players
    usage: /<command> <playername>
  removeprotection:
    description: Used if you want to remove your newbie status early
    usage: /<command>
  curezombie:
    description: Cures zombieness
    usage: /<command> <player>
  spawnboss:
    description: Spawns a boss mob at location
    usage: /<command> <mob type>
  lost:
    description: Gives you a compass if you need one
    usage: /<command>
  top:
    description: Shows the top 10 players
    usage: /<command>
    aliases: [hctop, htop, hct, ht]
  rank:
    description: Shows your or another player's rank and score
    usage: /<command> (player)
    aliases: [hcrank, hrank, hcr, hr]
  stats:
    description: View hardcore stats
    usage: /<command> (player)
    aliases: [hcstats, hstats, hcs, hs]