name: HardcoreSurvival
version: 1.0
main: me.becja10.HardcoreSurvival.Main
softdepend: [GriefPrevention]
description: Hardcore wrapper plugin for servers running GriefPrevention and Essentials
commands:
  setbase:
    description: Stores your location so that you can find your way back with a compass
    usage: /<command>